"""S4.5 / B-6 — the D18 birth gate: the differ-fixture validates and the schema is born (inv 23).

``tests/fixtures/structure/differ_structure_map.json`` is the **hand-authored, conforming**
second-structure fixture built to DIFFER from PLL (s4_plan §1.2, tracker S4.5): depth-0 body (every
child of the root is a leaf — no parts/chapters), ``designation-string`` handle policy throughout,
non-ordinal headings ("Of Silence", not "Capitolo Primo"), **mismatched body segmentation** (two
aphorisms own *interleaved* canonical atoms — a block structure PLL's contiguous chapters never
produce), alias-uniqueness-in-scope (one retired-handle value active in two scopes, resolving to two
different nodes), and the relation-endpoint **placeholder only** (the manifest's ``relation_store``
layer pinned ``present:false`` — endpoint *resolution* is S7/S9.4, R2-03). It is the SAME
adversarial fixture S9.4 later drives end-to-end, and it is distinct from ``books/synthetic`` (a
miniature PLL).

The schema's defining correctness property — that it is *not PLL-overfit* — is established ONLY by
this fixture validating (§1.2.1). The gate's assertion form is **two unconditional asserts** (X10):
a literal ``(status == born) == validates`` biconditional would sit green in the
provisional-AND-broken quadrant. The ``schema_status`` flip provisional→born is a deliberate human
edit to ``artifacts.STRUCTURE_MAP_SCHEMA_STATUS`` (§1.2.2), made at B-6 once this fixture first
validated — this test asserts the flip happened; it never mutates the status itself.

Red history + named mutations (inv 23):
  - assert 1 was seen red during authoring (the fixture initially referenced atoms absent from the
    differ store — ``StructureValidationError`` until the store matched); the standing named
    mutation is: drop a required Node field from ``differ_structure_map.json`` (Tier-1 red) or
    strand one included atom (``UNOWNED_INCLUDED_ATOM``, Tier-2 red).
  - assert 2 was seen red before the flip (status ``provisional`` → the equality failed), which is
    exactly the gate: green requires BOTH a validating differ-fixture AND the ratified flip.
  - the ``SCHEMA_NOT_BORN`` negative + missing-key fail-safe reds live in
    ``test_structure_map.py`` (they monkeypatch the status, so they are flip-agnostic).

The differ-fixture is hand-authored and MUST NOT be regenerated by the path it validates (§ inv 23)
— there is deliberately no generator for it; the shape-pin tests below keep a future edit from
quietly PLL-ifying it (depth, policy, interleaving, scoped aliases).
"""

from __future__ import annotations

import json
from pathlib import Path

import engine.structure as structure
from engine.structure import (
    PROCESSING_SCOPE_EXCLUDED,
    PROCESSING_SCOPE_INCLUDED,
    ContainerNode,
    LeafNode,
)
from engine.structure.artifacts import (
    SCHEMA_STATUS_BORN,
    STRUCTURE_MAP_SCHEMA_STATUS,
    STRUCTURE_MAP_SCHEMA_VERSION,
)
from engine.structure.handles import POLICY_DESIGNATION

DIFFER = Path(__file__).resolve().parents[1] / "fixtures" / "structure" / "differ_structure_map.json"

#: The differ book's atom universe: five included canonical atoms + two excluded witness furniture
#: atoms (running head / catchword — furniture *roles* PLL's page-number profile never mints).
_INCLUDED = ("dc_00000", "dc_00001", "dc_00002", "dc_00003", "dc_00004")
_EXCLUDED = ("wf_00000", "wf_00003")


class _DifferStore:
    def included_atom_ids(self):
        return _INCLUDED

    def contains(self, atom_id):
        return atom_id in _INCLUDED or atom_id in _EXCLUDED

    def scope_of(self, atom_id):
        if atom_id in _INCLUDED:
            return PROCESSING_SCOPE_INCLUDED
        if atom_id in _EXCLUDED:
            return PROCESSING_SCOPE_EXCLUDED
        return None


def _load():
    return structure.load_structure_map(DIFFER, _DifferStore())


# --- inv 23 — the birth gate: TWO UNCONDITIONAL ASSERTS (X10) ------------------------------------- #


def test_differ_fixture_validates_and_the_schema_is_born():
    # Assert 1 (unconditional): the differ-fixture shape- AND semantically-validates through the
    # born-agnostic loader — load_structure_map raises on any tier's failure, so a returned map IS
    # the validation proof; the explicit assert pins that a real map came back.
    smap = _load()
    assert isinstance(smap, structure.StructureMap)
    # Assert 2 (unconditional): the current schema version is BORN — the ratified human flip in
    # artifacts.STRUCTURE_MAP_SCHEMA_STATUS. Neither assert is conditioned on the other (X10): a
    # broken fixture reds assert 1 even after the flip; a validating fixture with no flip reds here.
    assert STRUCTURE_MAP_SCHEMA_STATUS[STRUCTURE_MAP_SCHEMA_VERSION] == SCHEMA_STATUS_BORN


def test_born_gate_passes_after_the_flip():
    # The gate function itself (the SCHEMA_NOT_BORN producer) accepts the born schema — the
    # complement of test_structure_map's monkeypatched provisional/missing-key negatives.
    structure.assert_schema_born()  # no raise


# --- differ-shape pins: the fixture stays a NON-PLL shape ------------------------------------------ #


def test_differ_is_depth_zero_every_root_child_is_a_leaf():
    smap = _load()
    root = smap.projection.by_id[smap.projection.root_id]
    assert isinstance(root, ContainerNode)
    assert root.children, "the differ root must have children (depth-0 body, not an empty codex)"
    for child in root.children:
        assert isinstance(smap.projection.by_id[child], LeafNode), (
            f"{child!r} is not a leaf — the differ-fixture must stay depth-0 (no PLL part/chapter tiers)"
        )


def test_differ_policy_is_designation_string_not_position_path():
    smap = _load()
    assert set(smap.handle_policies.values()) == {POLICY_DESIGNATION}


def test_differ_headings_are_non_ordinal():
    # Non-ordinal designations: none carries a digit and none is empty — the shape that forces the
    # schema/renderer to work without PLL's ordinal-word grammar.
    smap = _load()
    designations = [n.designation for n in smap.projection.nodes if isinstance(n, LeafNode)]
    assert designations and all(d for d in designations)
    assert not any(any(ch.isdigit() for ch in d) for d in designations)


def test_differ_body_segmentation_is_interleaved():
    # The "mismatched body segmentation" arm: two leaves own INTERLEAVED slices of the canonical
    # stream (each strictly ascending, jointly non-contiguous) — PLL's contiguous chapters never
    # produce this, so a schema/validator overfitted to contiguity would reject it here.
    smap = _load()
    index = {atom_id: i for i, atom_id in enumerate(_INCLUDED)}
    spans = {
        node.node_id: [index[a] for a in node.body_atoms]
        for node in smap.projection.nodes
        if isinstance(node, LeafNode)
    }
    one, two = spans["aph-one"], spans["aph-two"]
    assert one == sorted(one) and two == sorted(two)  # each leaf ascending (inv 27 holds)
    assert one[0] < two[0] < one[1] < two[1], f"expected interleaving, got {one} / {two}"


def test_differ_alias_value_is_scope_disambiguated():
    # Alias-uniqueness-in-scope: the SAME retired-handle value is active in two scopes and resolves
    # to two DIFFERENT nodes — scope is part of the uniqueness key, not decoration.
    smap = _load()
    kwargs = dict(handle_type="html_slug", value="of-silence", locale_or_witness="default")
    global_hit = structure.resolve(smap.projection, smap.aliases, scope="global", **kwargs)
    scoped_hit = structure.resolve(smap.projection, smap.aliases, scope="d-root", **kwargs)
    assert global_hit == "aph-one"
    assert scoped_hit == "aph-two"
    assert global_hit != scoped_hit


def test_differ_relation_layer_is_a_placeholder_not_a_resolution():
    # R2-03: the fixture carries the relation-endpoint PLACEHOLDER only — the manifest's
    # relation_store layer, pinned present:false (resolution is S7/S9.4).
    doc = json.loads(DIFFER.read_text(encoding="utf-8"))
    assert doc["manifest"]["layers"]["relation_store"]["present"] is False
