"""S4.5 / B-6 — the D18 birth gate: the differ-fixture validates and the schema is born (inv 23).

``tests/fixtures/structure/differ_structure_map.json`` is the **hand-authored, conforming**
second-structure fixture built to DIFFER from PLL (s4_plan §1.2, tracker S4.5): depth-0 body (every
child of the root is a leaf — no parts/chapters), ``designation-string`` handle policy throughout,
non-ordinal headings ("Of Silence", not "Capitolo Primo"), **mismatched body segmentation** (two
aphorisms own *interleaved* canonical atoms — a block structure PLL's contiguous chapters never
produce), alias-uniqueness-in-scope (one retired-handle value active in two scopes, resolving to two
different nodes), and the relation-endpoint **placeholder only** (the manifest's ``relation_store``
layer pinned ``present:false`` — endpoint *resolution* is S7/S9.4, R2-03). It is the SAME
adversarial fixture S9.4 later drives end-to-end, and it is distinct from ``books/synthetic`` (a
miniature PLL).

**Upgraded to real streams (2026-07-02, user-ratified — the first progressive step toward S9.4).**
The differ book now has hand-authored raw witness sources (``differ_witness_a.txt`` /
``differ_witness_b.txt``; witness A carries a running-head and a catchword — furniture *roles*
PLL's page-number profile never mints), and this gate builds its atom store through the REAL
producers (``capture_witness`` → ``build_canonical`` → ``AtomStream`` → ``StreamAtomReader``)
instead of a hand-rolled duck store. The committed map's manifest values are **live-bound**: a test
below recomputes the manifest via ``build_manifest`` over the captured streams and asserts byte
equality — so the hand-authored fixture cannot drift from what the producers would stamp. What
S9.4 still adds (owned there, not here): a structure *profile* for the differ book (S9.1) and the
recognizer drive from raw (S9.2) — this file proves schema + loader + store; S9.4 proves the
extractor.

The schema's defining correctness property — that it is *not PLL-overfit* — is established ONLY by
this fixture validating (§1.2.1). The gate's assertion form is **two unconditional asserts** (X10):
a literal ``(status == born) == validates`` biconditional would sit green in the
provisional-AND-broken quadrant. The ``schema_status`` flip provisional→born is a deliberate human
edit to ``artifacts.STRUCTURE_MAP_SCHEMA_STATUS`` (§1.2.2), made at B-6 once this fixture first
validated and ratified by the user 2026-07-02 — this test asserts the flip happened; it never
mutates the status itself.

Red history + named mutations (inv 23):
  - assert 1 was seen red during authoring (fixture↔store mismatches red the load); the standing
    named mutation is: drop a required Node field from ``differ_structure_map.json`` (Tier-1 red)
    or strand one included atom (``UNOWNED_INCLUDED_ATOM``, Tier-2 red).
  - assert 2 was seen red before the flip (status ``provisional`` → the equality failed), which is
    exactly the gate: green requires BOTH a validating differ-fixture AND the ratified flip.
  - the manifest live-binding was seen red against placeholder hashes (the pre-upgrade fixture).
  - the ``SCHEMA_NOT_BORN`` negative + missing-key fail-safe reds live in
    ``test_structure_map.py`` (they monkeypatch the status, so they are flip-agnostic).

The differ-fixture is hand-authored and MUST NOT be regenerated by the path it validates (inv 23)
— there is deliberately no generator for it (the live-binding test VERIFIES the hand-authored
values against the producers; it does not produce them); the shape-pin tests below keep a future
edit from quietly PLL-ifying it (depth, policy, interleaving, scoped aliases).
"""

from __future__ import annotations

import json
from pathlib import Path

import engine.structure as structure
from engine.structure import ContainerNode, LeafNode
from engine.structure.artifacts import (
    SCHEMA_STATUS_BORN,
    STRUCTURE_MAP_SCHEMA_STATUS,
    STRUCTURE_MAP_SCHEMA_VERSION,
)
from engine.structure.handles import POLICY_DESIGNATION
from engine.structure.lineage import ResourceLineage, _canonical

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures" / "structure"
DIFFER = FIXTURES / "differ_structure_map.json"
WITNESS_A = FIXTURES / "differ_witness_a.txt"
WITNESS_B = FIXTURES / "differ_witness_b.txt"


def _classify_differ_furniture(line: str) -> str | None:
    """The differ book's furniture grammar (fixture-local, like every per-book classifier): the
    running head and the ``·``-decorated catchword line; everything else is body."""
    if line.strip() == "THE DIFFER CODEX":
        return "running-head"
    if line.strip().startswith("·"):
        return "catchword"
    return None


def _differ_streams() -> dict[str, structure.AtomStream]:
    """The differ book's atom store, built through the REAL producers from the committed sources."""
    src_a = WITNESS_A.read_text(encoding="utf-8")
    src_b = WITNESS_B.read_text(encoding="utf-8")
    atoms_a = structure.capture_witness(src_a, "wdiffer-a", classify_line=_classify_differ_furniture)
    atoms_b = structure.capture_witness(src_b, "wdiffer-b")
    canonical = structure.build_canonical(
        {"wdiffer-a": atoms_a, "wdiffer-b": atoms_b}, ("wdiffer-a", "wdiffer-b")
    )
    return {
        "wdiffer-a": structure.AtomStream.witness(
            "wdiffer-a", atoms_a, structure.gap_records(atoms_a, src_a), src_a
        ),
        "wdiffer-b": structure.AtomStream.witness(
            "wdiffer-b", atoms_b, structure.gap_records(atoms_b, src_b), src_b
        ),
        "canonical": structure.AtomStream.canonical(canonical),
    }


def _reader() -> structure.StreamAtomReader:
    return structure.StreamAtomReader(_differ_streams())


def _load():
    return structure.load_structure_map(DIFFER, _reader())


# --- inv 23 — the birth gate: TWO UNCONDITIONAL ASSERTS (X10) ------------------------------------- #


def test_differ_fixture_validates_and_the_schema_is_born():
    # Assert 1 (unconditional): the differ-fixture shape- AND semantically-validates through the
    # born-agnostic loader, over the REAL captured streams — load_structure_map raises on any
    # tier's failure, so a returned map IS the validation proof; the explicit assert pins that a
    # real map came back.
    smap = _load()
    assert isinstance(smap, structure.StructureMap)
    # Assert 2 (unconditional): the current schema version is BORN — the ratified human flip in
    # artifacts.STRUCTURE_MAP_SCHEMA_STATUS. Neither assert is conditioned on the other (X10): a
    # broken fixture reds assert 1 even after the flip; a validating fixture with no flip reds here.
    assert STRUCTURE_MAP_SCHEMA_STATUS[STRUCTURE_MAP_SCHEMA_VERSION] == SCHEMA_STATUS_BORN


def test_born_gate_passes_after_the_flip():
    # The gate function itself (the SCHEMA_NOT_BORN producer) accepts the born schema — the
    # complement of test_structure_map's monkeypatched provisional/missing-key negatives.
    structure.assert_schema_born()  # no raise


# --- inv 23 for v2 (S5.1): the fingerprint fixture births the widened v2 shape -------------------- #

REBIND_POSITIVE = FIXTURES / "rebind_positive_structure_map.json"


class _MiniStore:
    """A minimal §4-header reader for the hand-authored v2 fingerprint fixture — its atom universe
    is three included body atoms (a0/a1/a2), not the differ book's real streams. The v2 birth gate
    proves the widened *shape* validates; the real-stream backing stays the differ fixture's job."""

    def __init__(self, included: tuple[str, ...]) -> None:
        self._included = tuple(included)
        self._scope = {a: structure.PROCESSING_SCOPE_INCLUDED for a in included}

    def included_atom_ids(self) -> tuple[str, ...]:
        return self._included

    def contains(self, atom_id: str) -> bool:
        return atom_id in self._scope

    def scope_of(self, atom_id: str) -> str | None:
        return self._scope.get(atom_id)


def test_v3_boundary_anchor_fixture_validates_and_v3_is_born():
    # The v3 birth gate: a NON-PLL conforming map that populates stored slot boundary anchors
    # validates through the born-agnostic loader. Two unconditional asserts (X10): a
    # broken fixture reds assert 1 even after the flip; a validating fixture with no flip reds
    # assert 2 (the pre-flip red-first state).
    smap = structure.load_structure_map(REBIND_POSITIVE, _MiniStore(("a0", "a1", "a2")))
    assert isinstance(smap, structure.StructureMap)
    assert STRUCTURE_MAP_SCHEMA_STATUS[STRUCTURE_MAP_SCHEMA_VERSION] == SCHEMA_STATUS_BORN


def test_v3_birth_fixture_actually_carries_the_boundary_anchor_shape():
    # Non-vacuity guard: v3 birth must exercise the newly stored start/end anchor pairs.
    doc = json.loads(REBIND_POSITIVE.read_text(encoding="utf-8"))
    fingerprints = [
        node["rebind_anchors"]["content_fingerprint"]
        for node in doc["nodes"]
        if "content_fingerprint" in node.get("rebind_anchors", {})
    ]
    assert fingerprints, "the v2 birth fixture must POPULATE content_fingerprint (the v2 novelty)"
    assert any("body" in fp for fp in fingerprints), "expected a per-slot body fingerprint"
    boundary_anchors = [
        node["rebind_anchors"]["boundary_anchors"]
        for node in doc["nodes"]
        if "boundary_anchors" in node.get("rebind_anchors", {})
    ]
    assert boundary_anchors
    assert all({"start", "end"} <= set(pair["body"]) for pair in boundary_anchors)


# --- the manifest is live-bound: hand-authored values == what the producers stamp ------------------ #


def test_differ_manifest_matches_the_live_producers_over_the_committed_sources():
    # The hand-authored map's manifest (stream hashes, split canonical hashes, layers, renderer
    # version) must equal build_manifest's output over the captured streams — hand-authorship with
    # a live verification, NOT generation (inv 23: the fixture is never produced by the path it
    # validates). A drift in either direction — a source edit without a manifest refresh, or a
    # producer change (hash field list, layer stamping) without a fixture refresh — reds here.
    doc = json.loads(DIFFER.read_text(encoding="utf-8"))
    fragment = doc["manifest"]["resource_lineage"]
    lineage = ResourceLineage(
        resource_version=fragment["resource"]["version"],
        resource_descriptor=_canonical(fragment["resource"]["descriptor"]),
        resource_stale_class=fragment["resource"]["stale_class"],
        normalizer_version=fragment["normalizer"]["version"],
        normalizer_descriptor=_canonical(fragment["normalizer"]["descriptor"]),
        normalizer_stale_class=fragment["normalizer"]["stale_class"],
    )
    live = structure.build_manifest(
        streams=_differ_streams(),
        canonical_stream_id="canonical",
        resource_lineage=lineage,
        profile_version=doc["manifest"]["profile_version"],
        recognizer_version=doc["manifest"]["recognizer_version"],
    )
    assert doc["manifest"] == live


def test_differ_furniture_is_real_witness_furniture():
    # The furniture entries resolve to genuinely EXCLUDED atoms in the captured witness stream —
    # the §3.B.1 witness-id namespace exercised against real capture output, with furniture roles
    # (running-head, catchword) PLL's page-number profile never mints.
    streams = _differ_streams()
    doc = json.loads(DIFFER.read_text(encoding="utf-8"))
    excluded = {
        a.atom_id: a.capture_provenance_class
        for a in streams["wdiffer-a"].atoms
        if a.processing_scope == structure.PROCESSING_SCOPE_EXCLUDED
    }
    declared = {f["atom_id"]: f["capture_role"] for f in doc["furniture_atoms"]}
    assert declared == excluded  # same atoms, same roles — capture and map agree exactly


# --- differ-shape pins: the fixture stays a NON-PLL shape ------------------------------------------ #


def test_differ_is_depth_zero_every_root_child_is_a_leaf():
    smap = _load()
    root = smap.projection.by_id[smap.projection.root_id]
    assert isinstance(root, ContainerNode)
    assert root.children, "the differ root must have children (depth-0 body, not an empty codex)"
    for child in root.children:
        assert isinstance(smap.projection.by_id[child], LeafNode), (
            f"{child!r} is not a leaf — the differ-fixture must stay depth-0 (no PLL part/chapter tiers)"
        )


def test_differ_policy_is_designation_string_not_position_path():
    smap = _load()
    assert set(smap.handle_policies.values()) == {POLICY_DESIGNATION}


def test_differ_headings_are_non_ordinal():
    # Non-ordinal designations: none carries a digit and none is empty — the shape that forces the
    # schema/renderer to work without PLL's ordinal-word grammar.
    smap = _load()
    designations = [n.designation for n in smap.projection.nodes if isinstance(n, LeafNode)]
    assert designations and all(d for d in designations)
    assert not any(any(ch.isdigit() for ch in d) for d in designations)


def test_differ_body_segmentation_is_interleaved():
    # The "mismatched body segmentation" arm: two leaves own INTERLEAVED slices of the canonical
    # stream (each strictly ascending, jointly non-contiguous) — PLL's contiguous chapters never
    # produce this, so a schema/validator overfitted to contiguity would reject it here. The index
    # is the REAL canonical order from the captured streams.
    reader = _reader()
    smap = structure.load_structure_map(DIFFER, reader)
    index = {atom_id: i for i, atom_id in enumerate(reader.included_atom_ids())}
    spans = {
        node.node_id: [index[a] for a in node.body_atoms]
        for node in smap.projection.nodes
        if isinstance(node, LeafNode)
    }
    one, two = spans["aph-one"], spans["aph-two"]
    assert one == sorted(one) and two == sorted(two)  # each leaf ascending (inv 27 holds)
    assert one[0] < two[0] < one[1] < two[1], f"expected interleaving, got {one} / {two}"


def test_differ_alias_value_is_scope_disambiguated():
    # Alias-uniqueness-in-scope: the SAME retired-handle value is active in two scopes and resolves
    # to two DIFFERENT nodes — scope is part of the uniqueness key, not decoration.
    smap = _load()
    kwargs = dict(handle_type="html_slug", value="of-silence", locale_or_witness="default")
    global_hit = structure.resolve(smap.projection, smap.aliases, scope="global", **kwargs)
    scoped_hit = structure.resolve(smap.projection, smap.aliases, scope="d-root", **kwargs)
    assert global_hit == "aph-one"
    assert scoped_hit == "aph-two"
    assert global_hit != scoped_hit


def test_differ_relation_layer_is_a_placeholder_not_a_resolution():
    # R2-03: the fixture carries the relation-endpoint PLACEHOLDER only — the manifest's
    # relation_store layer, pinned present:false (resolution is S7/S9.4).
    doc = json.loads(DIFFER.read_text(encoding="utf-8"))
    assert doc["manifest"]["layers"]["relation_store"]["present"] is False
