"""S2.0 — bbox + text↔box-alignment PROBE (GATE, issue #18; ENGINE_STRUCTURE_TASKS S2.0).

Reproducible evidence for the geometry-pole gate. Revised after the 5-lens adversarial audit
(2026-06-29) — see `docs/probes/s2_0_adversarial_audit.md`. Measures, on real PLL pages:

  (i)  does a usable OCR word-box layer EXIST?
       Native `get_text` on both source PDFs is empty (image scans), so a box layer is GENERATED by
       a fresh PyMuPDF+Tesseract(ita) OCR pass — a different engine from every witness.

  (ii) can those boxes be TRUSTED as anchors for the witness text?
       The boxes come from a *different* OCR engine than every witness (copy1/2 = IA-Tesseract,
       copy3 = Gemini), so "an atom carries its primary witness's box" is a cross-engine match.
       copy3 (Gemini) is the only witness with a per-page char map, so it is the alignment target;
       copy1 was independently confirmed column-ordered (audit), so copy3 is representative.

Coverage numbers reported per page (token = whitespace split, lowercased, edge-punct stripped):
  - BoW              : multiset overlap, order-independent  -> token-anchorability ceiling
  - content BoW      : BoW over distinctive tokens only (function words dropped) -> what re-bind gets
  - naive ordered    : LCS coverage in raw OCR (full-width) reading order
  - col-aware ordered: LCS coverage after recovering column reading order from the box COORDINATES

Reading order on PLL's two-column body collapses naive ordered to ~0.50 (full-width OCR interleaves
the columns); recovering column order from the box coordinates lifts it back toward the BoW ceiling.

COLUMN DETECTION HERE is a projection-profile gutter test (contiguous central low-density run, near
page-center, splitting the page into two substantially-populated halves) — a real improvement over the
audit-killed `min(single-bin)` detector (which flagged EVERY page two-column), but still a PROBE
heuristic, not the production matcher. It has known residual edge errors (a few sparse back-matter /
footnote pages); those are reported, not hidden. A robust single-vs-N-column detector is S2.1 work.

Reading order is NOT, in general, the geometry's job: when a column-correct text witness exists (PLL),
it is the reading-order oracle and boxes position-match it; the geometric detector is a cross-check.
When no prior witness exists (image-only source), the geometric detector is the primary order source,
backstopped by human-in-the-loop review of low-confidence pages.

Run (Tesseract tessdata must be discoverable):
    cd engine && TESSDATA_PREFIX=/opt/homebrew/share/tessdata \
      uv run python books/per_la_liberta/probes/s2_0_geometry_probe.py [out.json]
Override inputs via env: PLL_LOC_PDF (default repo-root LOC scan), PLL_OCR_DPI (default 300).
"""
from __future__ import annotations

import json
import os
import re
import statistics
import sys
import time
from collections import Counter
from difflib import SequenceMatcher
from pathlib import Path

import fitz  # PyMuPDF — declared engine dependency

BOOK = Path(__file__).resolve().parents[1]
PDF = Path(os.environ.get(
    "PLL_LOC_PDF",
    BOOK.parents[2] / "public-gdcmassbookdig-perlalibertdal00cres-perlalibertdal00cres.pdf",
))
COPY3 = BOOK / "inputs" / "copy3_raw.txt"
PAGEMAP = BOOK / "inputs" / "copy3_pro_page_map.json"
DPI = int(os.environ.get("PLL_OCR_DPI", "300"))
OCR_LANG = "ita"
PRIMARY_BAR = 0.85  # the pre-registered "geometry usable as S5 primary" per-page bar

# scan_page (1-indexed PDF page) -> stratum. Labels corrected after the audit: 269 is a clean small-type
# TOC (not a "bad-OCR region" — that stratum was not located); 189/193 are Orsini-section narrative
# prose (no set-off embedded letters were found in the book); 125/126 are part dividers (near-empty).
STRATIFIED = [
    (5, "front_matter_1col"), (6, "near_blank_verso"),
    (7, "chapter_open_1col"), (9, "chapter_open_2col"), (127, "chapter_open_2col"),
    (21, "dense_prose"), (28, "dense_prose"), (57, "dense_prose"),
    (140, "dense_prose"), (204, "dense_prose"),
    (72, "footnote_callout"), (73, "footnote_body"), (82, "footnote_body"),
    (125, "part_divider"), (126, "part_divider"),
    (168, "low_coverage"), (231, "low_coverage"),
    (189, "orsini_prose"), (193, "orsini_prose"),
    (269, "toc_smalltype"),
]

_EDGE = re.compile(r"^[^0-9A-Za-zÀ-ÿ]+|[^0-9A-Za-zÀ-ÿ]+$")
_STOP = {
    "di", "a", "da", "in", "con", "su", "per", "tra", "fra", "il", "lo", "la", "i", "gli", "le",
    "un", "uno", "una", "e", "ed", "o", "od", "ma", "se", "che", "chi", "cui", "non", "né", "come",
    "più", "meno", "anche", "ancora", "già", "del", "della", "dei", "delle", "degli", "dello",
    "al", "alla", "ai", "alle", "agli", "allo", "dal", "dalla", "dai", "dalle", "nel", "nella",
    "nei", "nelle", "negli", "nello", "sul", "sulla", "sui", "col", "si", "ci", "vi", "ne", "mi",
    "ti", "li", "è", "era", "erano", "sono", "ho", "ha", "hanno", "essere", "aveva", "suo", "sua",
    "suoi", "sue", "loro", "questo", "questa", "quel", "quella", "quei", "quelle", "tutto", "tutti",
    "ogni", "fu", "ove", "vi", "lor", "ei", "ed",
}


def tokens(text: str) -> list[str]:
    return [n for n in (_EDGE.sub("", t).lower() for t in text.split()) if n]


def content_tokens(toks: list[str]) -> list[str]:
    return [t for t in toks if t not in _STOP and len(t) > 2 and not t.isdigit()]


def ordered_coverage(wit: list[str], seq: list[str]) -> float:
    if not wit:
        return float("nan")
    sm = SequenceMatcher(a=wit, b=seq, autojunk=False)
    return sum(n for _, _, n in sm.get_matching_blocks()) / len(wit)


def bow_coverage(wit: list[str], seq: list[str]) -> float:
    if not wit:
        return float("nan")
    oc = Counter(seq)
    wc = Counter(wit)
    return sum(min(wc[w], oc[w]) for w in wc) / len(wit)


def detect_columns(words, width: float) -> tuple[int, float]:
    """(n_cols, split_x) via a projection-profile gutter test.

    Two-column iff a CONTIGUOUS run of central low-density bins (a real gutter), located NEAR the
    page center, splits the boxes into two SUBSTANTIALLY-populated halves. This rejects the audit's
    failure mode — a single stray empty bin in sparse single-column text reading as a "gutter".
    Still a probe heuristic with residual edge errors; a robust detector is S2.1.
    """
    if len(words) < 25:
        return (1, width)
    bins = [0] * 100
    for w in words:
        bins[max(0, min(99, int(((w[0] + w[2]) / 2) / width * 100)))] += 1   # clamp BOTH ends
    low = 0.15 * (max(bins) or 1)
    best_len = best_start = run = 0
    start = 33
    for b in range(33, 67):                          # central third only
        if bins[b] <= low:
            if run == 0:
                start = b
            run += 1
            if run > best_len:
                best_len, best_start = run, start
        else:
            run = 0
    if best_len < 3:                                 # need a real (>=3-bin) contiguous gutter
        return (1, width)
    split = (best_start + best_len / 2) / 100 * width
    if not (0.40 * width <= split <= 0.60 * width):  # gutter must be near center
        return (1, width)
    left = sum(1 for w in words if (w[0] + w[2]) / 2 < split) / len(words)
    if 0.28 <= left <= 0.72:                         # both columns genuinely populated
        return (2, split)
    return (1, width)


def reading_order(words, width: float) -> tuple[list[str], int]:
    """Recover reading order from box COORDINATES alone via detect_columns."""
    if not words:
        return ([], 1)
    n_cols, split = detect_columns(words, width)
    heights = [w[3] - w[1] for w in words]
    med = statistics.median(heights)
    line_h = (med if med > 0 else 10) * 0.6          # explicit guard (no falsy-zero `or`)

    def key(w):
        return (round(((w[1] + w[3]) / 2) / line_h), w[0])

    if n_cols == 2:
        left = sorted([w for w in words if (w[0] + w[2]) / 2 < split], key=key)
        right = sorted([w for w in words if (w[0] + w[2]) / 2 >= split], key=key)
        seq = left + right
    else:
        seq = sorted(words, key=key)
    return ([w[4] for w in seq], n_cols)


def box_smoke(words, rect) -> tuple[float, float]:
    """(boxes_in_page, vmono) — a SMOKE TEST that OCR ran, not an anchorability signal.

    OCR boxes are inside the page they were OCR'd from by construction, so boxes_in_page is ~1.0
    even for hallucinated noise boxes; it is reported only to confirm the geometry is well-formed.
    The real anchorability evidence is the witness coverage metrics.
    """
    if not words:
        return (1.0, 1.0)
    in_bounds = sum(
        1 for w in words
        if w[0] >= -1 and w[1] >= -1 and w[2] <= rect.width + 1 and w[3] <= rect.height + 1
        and w[2] > w[0] and w[3] > w[1]
    ) / len(words)
    tops = [w[1] for w in words]
    mono = sum(1 for a, b in zip(tops, tops[1:]) if b >= a - 2) / max(1, len(tops) - 1)
    return (in_bounds, mono)


def ocr_words(doc, scan: int):
    pg = doc[scan - 1]
    tp = pg.get_textpage_ocr(flags=0, language=OCR_LANG, dpi=DPI, full=True)
    return pg.get_text("words", textpage=tp), pg.rect


def measure(doc, scan: int, copy3: str, pm: dict):
    """All per-page metrics for one scan page."""
    words, rect = ocr_words(doc, scan)
    cs, ce = pm.get(scan, (None, None))
    wit = tokens(copy3[cs:ce]) if cs is not None else []
    ocr_tok = tokens(" ".join(w[4] for w in words))
    seq, n_cols = reading_order(words, rect.width)
    inb, vmono = box_smoke(words, rect)
    return {
        "scan": scan, "boxes": len(words), "wit_tokens": len(wit), "n_cols": n_cols,
        "bow": bow_coverage(wit, ocr_tok),
        "content_bow": bow_coverage(content_tokens(wit), content_tokens(ocr_tok)),
        "naive_ordered": ordered_coverage(wit, ocr_tok),
        "colaware_ordered": ordered_coverage(wit, tokens(" ".join(seq))),
        "boxes_in_page": inb, "vmono": vmono,
        "box_wit_ratio": len(words) / max(1, len(wit)),
    }


def _agg(rows: list[dict], field: str) -> dict:
    vals = [r[field] for r in rows if r[field] == r[field]]  # drop nan
    if not vals:
        return {"n": 0}
    return {
        "n": len(vals), "median": round(statistics.median(vals), 3),
        "mean": round(statistics.mean(vals), 3), "min": round(min(vals), 3),
        "pass@0.85": round(sum(v >= PRIMARY_BAR for v in vals) / len(vals), 3),
    }


def run():
    copy3 = COPY3.read_text(encoding="utf-8")
    pm = {e["page"]: (e["char_start"], e["char_end"]) for e in json.loads(PAGEMAP.read_text())}
    doc = fitz.open(PDF)
    out = {"pdf": PDF.name, "pages": doc.page_count, "dpi": DPI, "lang": OCR_LANG,
           "primary_bar": PRIMARY_BAR, "stratified": [], "sweep": []}

    print(f"# S2.0 geometry probe  pdf={PDF.name} pages={doc.page_count} dpi={DPI}\n")
    print("## stratified sample")
    hdr = f"{'scan':>4} {'stratum':<18} {'box':>4} {'wit':>4} {'cols':>4} {'BoW':>5} {'cBoW':>5} {'naive':>5} {'colaw':>5} {'b/w':>5}"
    print(hdr)
    for scan, stratum in STRATIFIED:
        t0 = time.time()
        r = measure(doc, scan, copy3, pm)
        r["stratum"] = stratum
        r["secs"] = round(time.time() - t0, 1)
        out["stratified"].append(r)
        f = lambda x: f"{x:5.2f}" if x == x else "  nan"  # noqa: E731
        print(f"{scan:>4} {stratum:<18} {r['boxes']:>4} {r['wit_tokens']:>4} {r['n_cols']:>4} "
              f"{f(r['bow'])} {f(r['content_bow'])} {f(r['naive_ordered'])} {f(r['colaware_ordered'])} "
              f"{r['box_wit_ratio']:5.1f}")

    print("\n## book-wide breadth sweep (every 7th page, wit>=20) — ordered coverage now computed")
    for scan in range(7, doc.page_count, 7):
        if scan not in pm:
            continue
        r = measure(doc, scan, copy3, pm)
        if r["wit_tokens"] < 20:
            continue
        out["sweep"].append(r)

    sweep = out["sweep"]
    two_col = [r for r in sweep if r["n_cols"] == 2]
    out["summary"] = {
        "sweep_n": len(sweep),
        "sweep_two_col_detected": len(two_col),
        "bow": _agg(sweep, "bow"),
        "content_bow": _agg(sweep, "content_bow"),
        "naive_ordered": _agg(sweep, "naive_ordered"),
        "colaware_ordered": _agg(sweep, "colaware_ordered"),
        "colaware_ordered_two_col_only": _agg(two_col, "colaware_ordered"),
    }
    s = out["summary"]
    print("\n## summary (breadth sweep is the honest basis — ordered coverage on n>=30)")
    print(f"sweep n={s['sweep_n']}  two-column detected={s['sweep_two_col_detected']}/{s['sweep_n']}")
    for k in ("bow", "content_bow", "naive_ordered", "colaware_ordered", "colaware_ordered_two_col_only"):
        a = s[k]
        print(f"  {k:<32} median={a.get('median')}  mean={a.get('mean')}  "
              f"min={a.get('min')}  pass@{PRIMARY_BAR}={a.get('pass@0.85')}  n={a.get('n')}")

    if len(sys.argv) > 1:
        Path(sys.argv[1]).write_text(json.dumps(out, indent=2))
        print(f"\nwrote {sys.argv[1]}")


if __name__ == "__main__":
    run()
