"""S2.0 — bbox + text↔box-alignment PROBE (GATE, issue #18; ENGINE_STRUCTURE_TASKS S2.0).

Reproducible evidence for the geometry-pole gate. Measures, on real PLL pages:

  (i)  does a usable OCR word-box layer EXIST?
       Native `get_text` on both source PDFs is empty (image scans), so a box layer must be
       GENERATED by a fresh PyMuPDF+Tesseract(ita) OCR pass. We measure that the generated boxes
       are valid (in page bounds, positive area) and in reading order.

  (ii) can those boxes be TRUSTED as anchors for the witness text?
       The boxes come from a *different* OCR engine than every witness (copy1/2 = IA-Tesseract,
       copy3 = Gemini), so "an atom carries its primary witness's box" is a cross-engine match.
       copy3 (Gemini) is the only witness with a per-page char map, so it is the alignment target
       — and the hardest one (a different OCR architecture entirely).

Three coverage numbers are reported per page:
  - BoW            : multiset token overlap, order-independent  -> token-anchorability CEILING
  - naive ordered  : LCS coverage in raw OCR (full-width) reading order
  - col-aware order: LCS coverage after recovering column reading order from the box COORDINATES

The gap between `naive` and `col-aware` is the whole finding: PLL's body is set in two columns,
so full-width OCR interleaves them and ordered coverage collapses to ~0.50, while the geometry's
own coordinates recover column reading order and lift it back to the BoW ceiling (~0.90).

The column-aware reorder here is a deliberately CRUDE probe heuristic (central-gutter split). It is
NOT the production matcher (that is S2.1); it exists only to demonstrate that the reading-order
signal is present in the geometry. It over-splits genuinely single-column pages (prefazione, cover,
index) — a production matcher needs real single-vs-N-column detection, which is the headline S2.1
requirement this probe surfaces.

Run (Tesseract tessdata must be discoverable):
    TESSDATA_PREFIX=/opt/homebrew/share/tessdata \
      uv run python books/per_la_liberta/probes/s2_0_geometry_probe.py [out.json]

Override inputs via env: PLL_LOC_PDF (default: repo-root LOC scan), PLL_OCR_DPI (default 300).
"""
from __future__ import annotations

import json
import os
import re
import statistics
import sys
import time
from collections import Counter
from difflib import SequenceMatcher
from pathlib import Path

import fitz  # PyMuPDF — declared engine dependency

BOOK = Path(__file__).resolve().parents[1]
PDF = Path(os.environ.get(
    "PLL_LOC_PDF",
    BOOK.parents[2] / "public-gdcmassbookdig-perlalibertdal00cres-perlalibertdal00cres.pdf",
))
COPY3 = BOOK / "inputs" / "copy3_raw.txt"
PAGEMAP = BOOK / "inputs" / "copy3_pro_page_map.json"
DPI = int(os.environ.get("PLL_OCR_DPI", "300"))
OCR_LANG = "ita"

# scan_page (1-indexed PDF page) -> stratum. Anchored to chapter_start_pages.json + a witness
# text scan (footnote/letter/dense pages located by pattern; see the S2.0 report for provenance).
STRATIFIED = [
    (5, "front_matter"), (6, "front_matter"),
    (7, "chapter_start"), (9, "chapter_start"), (127, "chapter_start"),
    (21, "dense_prose"), (57, "dense_prose"), (140, "dense_prose"), (204, "dense_prose"),
    (72, "footnotes"), (81, "footnotes"),
    (125, "page_furniture"), (126, "page_furniture"),
    (189, "embedded_letter"), (193, "embedded_letter"),
    (269, "bad_ocr_index"),
]

_EDGE = re.compile(r"^[^0-9A-Za-zÀ-ÿ]+|[^0-9A-Za-zÀ-ÿ]+$")


def tokens(text: str) -> list[str]:
    return [n for n in (_EDGE.sub("", t).lower() for t in text.split()) if n]


def ordered_coverage(wit: list[str], seq: list[str]) -> float:
    if not wit:
        return float("nan")
    sm = SequenceMatcher(a=wit, b=seq, autojunk=False)
    return sum(n for _, _, n in sm.get_matching_blocks()) / len(wit)


def bow_coverage(wit: list[str], seq: list[str]) -> float:
    if not wit:
        return float("nan")
    oc = Counter(seq)
    wc = Counter(wit)
    return sum(min(wc[w], oc[w]) for w in wc) / len(wit)


def gutter_emptiness(words, width: float) -> float | None:
    """Density of the emptiest x-center bin in the page's central band (low => two columns)."""
    if len(words) < 20:
        return None
    bins = [0] * 100
    for w in words:
        bins[min(99, int(((w[0] + w[2]) / 2) / width * 100))] += 1
    peak = max(bins) or 1
    return min(bins[b] for b in range(40, 60)) / peak


def box_validity(words, rect) -> tuple[float, float]:
    if not words:
        return (1.0, 1.0)
    in_bounds = sum(
        1 for w in words
        if w[0] >= -1 and w[1] >= -1 and w[2] <= rect.width + 1 and w[3] <= rect.height + 1
        and w[2] > w[0] and w[3] > w[1]
    ) / len(words)
    tops = [w[1] for w in words]
    mono = sum(1 for a, b in zip(tops, tops[1:]) if b >= a - 2) / max(1, len(tops) - 1)
    return (in_bounds, mono)


def reading_order(words, width: float) -> tuple[list[str], bool]:
    """Recover reading order from box COORDINATES alone (crude central-gutter heuristic)."""
    if not words:
        return ([], False)
    ge = gutter_emptiness(words, width)               # 0.0 is the STRONGEST two-column signal,
    two_col = ge is not None and ge < 0.06            # so test `is not None`, never `ge or ...`
    split = (min(range(40, 60), key=lambda b: _xhist(words, width)[b]) / 100 * width) if two_col else width
    line_h = (statistics.median([w[3] - w[1] for w in words]) or 10) * 0.6

    def key(w):
        return (round(((w[1] + w[3]) / 2) / line_h), w[0])

    if two_col:
        left = sorted([w for w in words if (w[0] + w[2]) / 2 < split], key=key)
        right = sorted([w for w in words if (w[0] + w[2]) / 2 >= split], key=key)
        seq = left + right
    else:
        seq = sorted(words, key=key)
    return ([w[4] for w in seq], two_col)


def _xhist(words, width: float) -> list[int]:
    bins = [0] * 100
    for w in words:
        bins[min(99, int(((w[0] + w[2]) / 2) / width * 100))] += 1
    return bins


def ocr_words(doc, scan: int):
    pg = doc[scan - 1]
    tp = pg.get_textpage_ocr(flags=0, language=OCR_LANG, dpi=DPI, full=True)
    return pg.get_text("words", textpage=tp), pg.rect


def run():
    copy3 = COPY3.read_text(encoding="utf-8")
    pm = {e["page"]: (e["char_start"], e["char_end"]) for e in json.loads(PAGEMAP.read_text())}
    doc = fitz.open(PDF)
    out = {"pdf": PDF.name, "pages": doc.page_count, "dpi": DPI, "lang": OCR_LANG,
           "stratified": [], "sweep": []}

    print(f"# S2.0 geometry probe  pdf={PDF.name} pages={doc.page_count} dpi={DPI}\n")
    print("## stratified sample")
    print(f"{'scan':>4} {'stratum':<15} {'boxes':>5} {'wit':>4} {'BoW':>5} {'naive':>5} "
          f"{'colaw':>5} {'inb':>4} {'vmono':>5} {'2col':>5}")
    for scan, stratum in STRATIFIED:
        t0 = time.time()
        words, rect = ocr_words(doc, scan)
        cs, ce = pm.get(scan, (None, None))
        wit = tokens(copy3[cs:ce]) if cs is not None else []
        naive = ordered_coverage(wit, tokens(" ".join(w[4] for w in words)))
        seq, two = reading_order(words, rect.width)
        colaw = ordered_coverage(wit, tokens(" ".join(seq)))
        bow = bow_coverage(wit, tokens(" ".join(w[4] for w in words)))
        inb, vmono = box_validity(words, rect)
        rec = {"scan": scan, "stratum": stratum, "boxes": len(words), "wit_tokens": len(wit),
               "bow": bow, "naive_ordered": naive, "colaware_ordered": colaw,
               "in_bounds": inb, "vmono": vmono, "two_col": two, "secs": round(time.time() - t0, 1)}
        out["stratified"].append(rec)
        print(f"{scan:>4} {stratum:<15} {len(words):>5} {len(wit):>4} {bow:5.2f} {naive:5.2f} "
              f"{colaw:5.2f} {inb:4.2f} {vmono:5.2f} {str(two):>5}")

    print("\n## book-wide sweep (every 7th page, wit>=20)")
    for scan in range(7, doc.page_count, 7):
        if scan not in pm:
            continue
        words, rect = ocr_words(doc, scan)
        cs, ce = pm[scan]
        wit = tokens(copy3[cs:ce])
        if len(wit) < 20:
            continue
        bow = bow_coverage(wit, tokens(" ".join(w[4] for w in words)))
        out["sweep"].append({"scan": scan, "wit_tokens": len(wit), "bow": bow,
                             "gutter": gutter_emptiness(words, rect.width)})

    body = [r for r in out["stratified"] if r["wit_tokens"] >= 20]
    bows = [r["bow"] for r in out["sweep"]]
    out["summary"] = {
        "stratified_body_median_naive": statistics.median([r["naive_ordered"] for r in body]),
        "stratified_body_median_colaware": statistics.median([r["colaware_ordered"] for r in body]),
        "stratified_body_median_bow": statistics.median([r["bow"] for r in body]),
        "sweep_n": len(bows),
        "sweep_bow_median": statistics.median(bows),
        "sweep_bow_mean": statistics.mean(bows),
        "sweep_bow_min": min(bows),
        "sweep_two_col_pages": sum(
            1 for r in out["sweep"] if r["gutter"] is not None and r["gutter"] < 0.12),
        "mean_in_bounds": statistics.mean([r["in_bounds"] for r in out["stratified"]]),
    }
    s = out["summary"]
    print(f"\n## summary\n"
          f"stratified body  median  naive={s['stratified_body_median_naive']:.3f}  "
          f"colaware={s['stratified_body_median_colaware']:.3f}  bow={s['stratified_body_median_bow']:.3f}\n"
          f"book-wide sweep  n={s['sweep_n']}  BoW median={s['sweep_bow_median']:.3f}  "
          f"mean={s['sweep_bow_mean']:.3f}  min={s['sweep_bow_min']:.3f}\n"
          f"two-column pages (sweep): {s['sweep_two_col_pages']}/{s['sweep_n']}\n"
          f"mean box in-bounds: {s['mean_in_bounds']:.3f}")

    if len(sys.argv) > 1:
        Path(sys.argv[1]).write_text(json.dumps(out, indent=2))
        print(f"\nwrote {sys.argv[1]}")


if __name__ == "__main__":
    run()
