"""S2.1.3 — the persisted geometry sidecar (``s2_1_plan.md`` DT-9; issue #37).

Geometry is L1 fact, but the frozen atom streams are what the user is actively authoring
against — S2.1 does **not** re-emit them. The matcher's output lands in a versioned **sidecar**
``books/<id>/work/data/geometry/{witness}_geom.json`` (gitignored ``work/data/``, disposable by
convention: the tracked verdict file + inputs regenerate it deterministically, DT-10). This module
owns the record vocabulary, the model invariants, the load/save boundary, and the P-5 auto-absent
tripwire; the matcher that *produces* the records is ``geom_match`` (which imports from here —
one-directional, never the reverse).

The model enforces the state split the plan pins (DT-8/DT-9):

- **Page records** — ``status ∈ {matched, routed, declined}``. A ``routed`` page's atoms are
  simply **absent from** ``atoms`` (*pending* ≠ ``Geom.absent`` — G-12); a ``declined`` page
  carries the human verdict on its page record (#40 writes it). Construction rejects an atom
  record whose assigned page is not ``matched`` — the absent-write-before-verdict fault is
  *unconstructible*, not merely untested.
- **Atom records** — ``status ∈ {matched, unmatched}``; the persisted unmatched ``reason`` enum is
  **closed** at three values (``zero_match`` / ``below_atom_floor`` / ``ambiguous``, R19). The
  attach-time outcomes (``ineligible``/``multi_primary_derivation``) are deliberately *not*
  admissible here — they are derived at ``attach_geometry`` from ``derived_from`` and can never be
  persisted as match failures (G-25).
- **``atom_pages``** — every stream atom's *derived* page window plus its assigned page: the DT-3
  byproduct (real page attribution for a ``PAGE_UNMAPPED`` witness, as derived sidecar data —
  never a frozen-stream mutation) and the map that lets ``attach_geometry`` tell a *pending* atom
  (assigned page routed) from a *declined* one without per-atom pending records.

Binding (R11): ``stream_source_hash`` pins the witness stream this sidecar matched
(``AtomStream.source_hash``); ``source_scan`` + ``backend_params``/``engine_id`` pin the scan and
the OCR pass the boxes came from. :func:`save_geom_sidecar` refuses to regenerate over an existing
sidecar whose scan identity disagrees, and :func:`assert_source_scan_matches` is the replay-side
check (G-19) — both the D14/D21 stale posture, so drift is loud, never silently absorbed.

Load boundary: the shared taxonomy (G-18) — an absent file is
:class:`~engine.errors.MissingInputError`; a present-but-unloadable/stale/malformed one is
:class:`~engine.errors.StaleArtifactError`; nothing else escapes the loader. The tripwire raises
:class:`~engine.structure.geometry.GeometryError` — an integrity gate, not a load fault.

Pure core: no language, book, or witness-name opinion lives here — witness ids, reasons for a
book's layout, and every threshold's *inputs* are caller-supplied (the S0.2 neutrality guard scans
this module). The P-5 tripwire constants are ruled algorithm parameters, value-pin tested.
"""

from __future__ import annotations

import json
import math
import re
from collections.abc import Mapping
from dataclasses import dataclass, replace
from pathlib import Path

from engine.errors import MissingInputError, StaleArtifactError
from engine.paths import BookWorkspace
from engine.structure.geometry import GeometryError
from engine.util.jsonio import atomic_write_json, read_json

#: Independent schema version of the geometry sidecar (M3 posture: one artifact, one version).
#: v2 (S2.1.6 / #40, DT-12) adds the segmentation-front-end detector fields to a matched page record
#: (``n_cols`` / ``n_cols_source`` / ``order_qa`` — the S2.2 measurement feed); a v1 file no longer
#: loads, which is correct (the sidecar is disposable and regenerated by the run).
GEOM_SIDECAR_SCHEMA_VERSION = 2
#: The envelope discriminator, so a load can reject a file that is structurally JSON but a
#: different persisted layer (the atom store / structure map / evidence sidecar all carry their
#: own). The sidecar is *disposable* (not S8.1-governed), so this is a wrong-artifact guard, not a
#: migration route — which is why it lives here beside its raiser, not in ``artifacts.py``'s
#: governed-layer roster.
GEOM_SIDECAR_STALE_CLASS = "geometry-sidecar"

#: Workspace area/subdir the sidecar lives under (``<work>/data/geometry/``) — an existing ignored
#: work area (R7), so nothing is added to ``paths._AREAS`` and containment is already enforced.
GEOMETRY_AREA = "data"
GEOMETRY_SUBDIR = "geometry"

# --- record vocabulary (closed sets — DT-9) ---------------------------------------------------- #

PAGE_MATCHED = "matched"
PAGE_ROUTED = "routed"
PAGE_DECLINED = "declined"
PAGE_STATUSES = (PAGE_MATCHED, PAGE_ROUTED, PAGE_DECLINED)

ATOM_MATCHED = "matched"
ATOM_UNMATCHED = "unmatched"
ATOM_STATUSES = (ATOM_MATCHED, ATOM_UNMATCHED)

#: The origin of a matched page's column count (DT-7/DT-9, schema v2): the page's own confident
#: detector verdict, or the cross-page prior inherited from an agreeing content neighbour. Mirrors
#: :class:`~engine.structure.segmentation.PageColumnVerdict`'s ``n_cols_source`` domain; a page with
#: no column decision carries ``None`` for both count and source.
N_COLS_SOURCES = ("evidence", "prior")

REASON_ZERO_MATCH = "zero_match"
REASON_BELOW_ATOM_FLOOR = "below_atom_floor"
REASON_AMBIGUOUS = "ambiguous"
#: The persisted unmatched-reason enum, **closed** at these three (R19): the attach-time outcomes
#: (``no_primary_derivation`` / ``multi_primary_derivation``) are derived from ``derived_from`` at
#: ``attach_geometry`` and must never be persisted as per-atom match failures (G-25/G-20).
UNMATCHED_REASONS = (REASON_ZERO_MATCH, REASON_BELOW_ATOM_FLOOR, REASON_AMBIGUOUS)

#: The four coverage counters DT-9 pins — loss counted separately and by cause, so the untried
#: secondary-witness lane stays visible as DT-13 evidence rather than silent coverage loss (R3).
COVERAGE_KEYS = (
    "pages_locate_failed",
    "atoms_unmatched_on_accepted_pages",
    "canonical_no_primary_derivation",
    "canonical_multi_primary_derivation",
)
#: The two canonical counters may be ``None`` — *unmeasured* (no canonical stream was given at
#: build), deliberately distinct from a measured 0 so a witness-only sidecar cannot masquerade as
#: "canonical fully covered" (they are DT-13's evidence, R3).
_NULLABLE_COVERAGE_KEYS = frozenset(
    {"canonical_no_primary_derivation", "canonical_multi_primary_derivation"}
)

# --- P-5 auto-absent tripwire constants (the two-leg form + warn tier RULED 2026-07-03; all four
# --- values pinned by test_tripwire_constants_are_the_ruled_p5_values, G-26) -------------------- #

#: Leg A: auto-absent token mass / accepted-page token mass may not exceed this. Sized against the
#: measured honest ceiling (the entire ≤3-token furniture tail is 1.3% of token mass, §2), so leg A
#: cannot fire on it even at total wipeout — any firing implies real prose mass absent.
TRIPWIRE_ABSENT_MASS_MAX = 0.02
#: Leg B scope: an atom is "prose-sized" for the tripwire at this many witness tokens or more.
TRIPWIRE_PROSE_MIN_TOKENS = 4
#: Leg B: the auto-absent *rate* among prose-sized atoms on accepted pages may not exceed this
#: (systematic absence, never honest residue). Catches the wide-but-thin failure leg A
#: underweights; leg A catches the mass-concentrated one leg B underweights.
TRIPWIRE_PROSE_ABSENT_RATE_MAX = 0.05
#: Warn tier (non-blocking): a token band whose auto-absent mass exceeds this fraction of
#: accepted-page token mass is flagged informationally in the returned stats.
TRIPWIRE_WARN_BAND_MASS = 0.01

# Same flat-stem discipline as the atom store's stream ids: the witness id lands in a filename
# template, so a path-shaped id (``../evil``, ``a/b``) is rejected at the model and the path
# accessor both — not merely blocked from escaping the workspace by ``resolve``'s containment.
_WITNESS_ID = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")


def _check_witness_id(witness_id: str) -> None:
    if not isinstance(witness_id, str) or not _WITNESS_ID.fullmatch(witness_id):
        raise ValueError(
            f"witness_id must be a flat filename stem matching {_WITNESS_ID.pattern!r}, got "
            f"{witness_id!r} — the sidecar is one {{witness}}_geom.json file, never a nested path"
        )


def _require(data: Mapping, key: str, ctx: str):
    """Fetch ``data[key]`` or fail loud as a malformed envelope (the load-boundary contract)."""
    if key not in data:
        raise StaleArtifactError(f"malformed geometry sidecar {ctx}: missing required key {key!r}")
    return data[key]


def _is_int(value) -> bool:
    # Exact-type: bool is an int subclass and True is not a page number or a count.
    return type(value) is int


def _is_rate(value) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool) and math.isfinite(value) and 0.0 <= value <= 1.0


# --- records ------------------------------------------------------------------------------------ #


@dataclass(frozen=True, slots=True)
class SourceScan:
    """The scan-identity fingerprint (R11): ``kind`` is the discriminator (``"pdf"`` today; a
    future image-bundle backend adds its own kind without a rename or version bump), ``sha256``
    the content hash, ``n_pages`` the page count, ``n_bytes`` the size (persisted as ``bytes``).
    All join the DT-10 input fingerprint; :func:`assert_source_scan_matches` is the replay check."""

    kind: str
    sha256: str
    n_pages: int
    n_bytes: int

    def __post_init__(self) -> None:
        if not (isinstance(self.kind, str) and self.kind.strip()):
            raise ValueError(f"source_scan.kind must be a non-empty discriminator, got {self.kind!r}")
        if not (isinstance(self.sha256, str) and self.sha256.strip()):
            raise ValueError("source_scan.sha256 must be a non-empty content hash")
        if not (_is_int(self.n_pages) and self.n_pages > 0):
            raise ValueError(f"source_scan.n_pages must be a positive integer, got {self.n_pages!r}")
        if not (_is_int(self.n_bytes) and self.n_bytes > 0):
            raise ValueError(f"source_scan.bytes must be a positive integer, got {self.n_bytes!r}")


@dataclass(frozen=True, slots=True)
class PageRecord:
    """One page's sidecar state (DT-9). The shape is status-conditional and enforced:

    - ``matched`` — ``match_rate`` required (the accepted page's atom-weighted rate); routing
      fields and ``verdict`` forbidden.
    - ``routed`` — ``stage``/``signal``/``value`` required (which gate fired and at what value);
      ``match_rate``/``verdict`` forbidden. The page's atoms are *pending*: absent from the atoms
      map, never written absent (G-12).
    - ``declined`` — ``verdict`` required (the human record, #40 writes it); everything else
      forbidden.

    ``dropped_boxes`` (the backend's DT-2 per-page normalization count) is a backend stat valid on
    any status; ``None`` means the producer had no count, which is distinct from ``0``.

    The detector fields (``n_cols``/``n_cols_source``/``order_qa`` — DT-9/DT-12, schema v2) are the
    segmentation front-end's per-page output on an **accepted** page: the resolved column count, its
    origin (own ``evidence`` or the cross-page ``prior``), and ``order_qa`` — the ordered coverage of
    the detector-ordered boxes against the witness window (the S2.2 measurement feed). They are
    forbidden on a routed/declined page (no accepted geometry to measure), and ``n_cols`` /
    ``n_cols_source`` are set together (a count has an origin, or both are absent — e.g. a
    matcher-built record before the detector wiring runs).
    """

    status: str
    match_rate: float | None = None
    dropped_boxes: int | None = None
    stage: str | None = None
    signal: str | None = None
    value: float | None = None
    verdict: Mapping | None = None
    n_cols: int | None = None
    n_cols_source: str | None = None
    order_qa: float | None = None

    def __post_init__(self) -> None:
        if self.status not in PAGE_STATUSES:
            raise ValueError(f"page status must be one of {PAGE_STATUSES}, got {self.status!r}")
        if self.dropped_boxes is not None and not (_is_int(self.dropped_boxes) and self.dropped_boxes >= 0):
            raise ValueError(f"dropped_boxes must be a non-negative integer or None, got {self.dropped_boxes!r}")
        self._check_detector_fields()
        if self.status == PAGE_MATCHED:
            if not _is_rate(self.match_rate):
                raise ValueError(f"a matched page requires match_rate in [0, 1], got {self.match_rate!r}")
            if self.stage is not None or self.signal is not None or self.value is not None or self.verdict is not None:
                raise ValueError("a matched page carries no routing fields or verdict")
        elif self.status == PAGE_ROUTED:
            if not (isinstance(self.stage, str) and self.stage.strip()):
                raise ValueError("a routed page requires the stage that routed it")
            if not (isinstance(self.signal, str) and self.signal.strip()):
                raise ValueError("a routed page requires the signal that routed it")
            if not (
                isinstance(self.value, (int, float))
                and not isinstance(self.value, bool)
                and math.isfinite(self.value)
            ):
                raise ValueError(f"a routed page requires the finite signal value, got {self.value!r}")
            if self.match_rate is not None or self.verdict is not None:
                raise ValueError("a routed page carries no match_rate or verdict (its atoms are pending)")
        else:  # declined
            if not (isinstance(self.verdict, Mapping) and self.verdict):
                raise ValueError("a declined page requires the non-empty human verdict record")
            if self.match_rate is not None or self.stage is not None or self.signal is not None or self.value is not None:
                raise ValueError("a declined page carries only its verdict")
            object.__setattr__(self, "verdict", dict(self.verdict))

    def _check_detector_fields(self) -> None:
        """The schema-v2 detector fields (DT-12): valid domains, coherent count↔source, and
        matched-only (a routed/declined page has no accepted geometry to measure)."""
        if self.n_cols is not None and not (_is_int(self.n_cols) and self.n_cols in (1, 2)):
            raise ValueError(f"n_cols must be 1, 2, or None, got {self.n_cols!r}")
        if self.n_cols_source is not None and self.n_cols_source not in N_COLS_SOURCES:
            raise ValueError(f"n_cols_source must be one of {N_COLS_SOURCES} or None, got {self.n_cols_source!r}")
        if (self.n_cols is None) != (self.n_cols_source is None):
            raise ValueError(
                "n_cols and n_cols_source are set together (a column count has a source, or both are absent), "
                f"got n_cols={self.n_cols!r} n_cols_source={self.n_cols_source!r}"
            )
        if self.order_qa is not None and not _is_rate(self.order_qa):
            raise ValueError(f"order_qa must be a rate in [0, 1] or None, got {self.order_qa!r}")
        if self.status != PAGE_MATCHED and (
            self.n_cols is not None or self.n_cols_source is not None or self.order_qa is not None
        ):
            raise ValueError(
                "only a matched page carries detector fields (n_cols/n_cols_source/order_qa) — a "
                f"{self.status!r} page has no accepted geometry to measure"
            )


@dataclass(frozen=True, slots=True)
class AtomRecord:
    """One accepted-page atom's match state (DT-8/DT-9). ``matched`` carries ``page`` + ``bbox``
    (the union over matched boxes only) + ``match_method``; ``unmatched`` carries a ``reason`` from
    the closed :data:`UNMATCHED_REASONS` enum and **no bbox** — absent, never a plausible wrong
    box. Both carry the measured ``match_confidence``."""

    status: str
    match_confidence: float
    page: int | None = None
    bbox: tuple[float, float, float, float] | None = None
    match_method: str | None = None
    reason: str | None = None

    def __post_init__(self) -> None:
        if self.status not in ATOM_STATUSES:
            raise ValueError(f"atom status must be one of {ATOM_STATUSES}, got {self.status!r}")
        if not _is_rate(self.match_confidence):
            raise ValueError(f"match_confidence must be in [0, 1], got {self.match_confidence!r}")
        if self.status == ATOM_MATCHED:
            if not (_is_int(self.page) and self.page > 0):
                raise ValueError(f"a matched atom requires its positive scan page, got {self.page!r}")
            if not isinstance(self.bbox, (tuple, list)) or len(self.bbox) != 4:
                raise ValueError(f"a matched atom requires a four-float bbox, got {self.bbox!r}")
            object.__setattr__(self, "bbox", tuple(float(c) for c in self.bbox))
            if not all(math.isfinite(c) for c in self.bbox):
                raise ValueError(f"bbox coordinates must be finite, got {self.bbox!r}")
            x0, y0, x1, y1 = self.bbox
            if x1 <= x0 or y1 <= y0:
                raise ValueError(f"bbox must be non-degenerate (x1 > x0 and y1 > y0), got {self.bbox!r}")
            if not (isinstance(self.match_method, str) and self.match_method.strip()):
                raise ValueError("a matched atom requires its match_method")
            if self.reason is not None:
                raise ValueError("a matched atom carries no unmatched reason")
        else:
            if self.reason not in UNMATCHED_REASONS:
                # The closed enum is load-bearing (R19/G-25): an attach-time outcome (ineligible /
                # multi-derivation) persisted here would silently become a match failure.
                raise ValueError(
                    f"an unmatched atom's reason must be one of {UNMATCHED_REASONS}, got {self.reason!r}"
                )
            if self.page is not None or self.bbox is not None or self.match_method is not None:
                raise ValueError("an unmatched atom carries no page/bbox/match_method — absent, never invented")


@dataclass(frozen=True, slots=True)
class AtomPages:
    """One stream atom's *derived* page attribution (the DT-3 byproduct): the window of scan pages
    its tokens overlap (``first``..``last``) and the single ``assigned`` page whose bag it matched
    against — the page whose record governs its state at ``attach_geometry``."""

    first: int
    last: int
    assigned: int

    def __post_init__(self) -> None:
        for name, value in (("first", self.first), ("last", self.last), ("assigned", self.assigned)):
            if not (_is_int(value) and value > 0):
                raise ValueError(f"atom_pages.{name} must be a positive scan page, got {value!r}")
        if not (self.first <= self.assigned <= self.last):
            raise ValueError(
                f"atom_pages must satisfy first <= assigned <= last, got "
                f"({self.first}, {self.assigned}, {self.last})"
            )


@dataclass(frozen=True, slots=True)
class GeomSidecar:
    """The whole persisted sidecar (DT-9), model-validated at construction.

    Cross-record invariants enforced here (so the faults are unconstructible, not merely
    untested): every atom record's atom must appear in ``atom_pages``; every ``atom_pages`` page
    must have a page record; an atom record's **assigned page must be ``matched``** — a routed or
    declined page's atoms are pending/declined by *absence* from the atoms map (G-12), and
    auto-absent records exist only on accepted pages (DT-8's scope split); a matched atom record's
    ``page`` must equal its assigned page.
    """

    witness_id: str
    stream_source_hash: str
    source_scan: SourceScan
    backend_params: Mapping[str, object]
    engine_id: str
    locate_method: str
    pages: Mapping[int, PageRecord]
    atoms: Mapping[str, AtomRecord]
    atom_pages: Mapping[str, AtomPages]
    coverage: Mapping[str, int | None]  # None only on the two canonical counters: "unmeasured"
    classifier_version: str | None = None
    classifier_params: Mapping[str, object] | None = None
    schema_version: int = GEOM_SIDECAR_SCHEMA_VERSION

    def __post_init__(self) -> None:
        _check_witness_id(self.witness_id)
        if not (isinstance(self.stream_source_hash, str) and self.stream_source_hash.strip()):
            raise ValueError("stream_source_hash must be the witness stream's non-empty source_hash anchor")
        if not isinstance(self.source_scan, SourceScan):
            raise ValueError(f"source_scan must be a SourceScan record, got {type(self.source_scan).__name__}")
        if not (isinstance(self.backend_params, Mapping) and self.backend_params):
            raise ValueError("backend_params must be the backend's non-empty structured contract (DT-9)")
        if not (isinstance(self.engine_id, str) and self.engine_id.strip()):
            raise ValueError("engine_id must be the backend's non-empty reproducibility string")
        if not (isinstance(self.locate_method, str) and self.locate_method.strip()):
            raise ValueError("locate_method must name the page-locate algorithm")
        object.__setattr__(self, "backend_params", dict(self.backend_params))
        object.__setattr__(self, "pages", dict(self.pages))
        object.__setattr__(self, "atoms", dict(self.atoms))
        object.__setattr__(self, "atom_pages", dict(self.atom_pages))
        object.__setattr__(self, "coverage", dict(self.coverage))
        if self.classifier_params is not None:
            object.__setattr__(self, "classifier_params", dict(self.classifier_params))
        if self.classifier_version is not None and not (
            isinstance(self.classifier_version, str) and self.classifier_version.strip()
        ):
            raise ValueError(f"classifier_version must be a non-empty string or None, got {self.classifier_version!r}")

        for page, record in self.pages.items():
            if not (_is_int(page) and page > 0):
                raise ValueError(f"pages must be keyed by positive scan page integers, got {page!r}")
            if not isinstance(record, PageRecord):
                raise ValueError(f"pages[{page}] must be a PageRecord, got {type(record).__name__}")
        for atom_id, window in self.atom_pages.items():
            if not (isinstance(atom_id, str) and atom_id):
                raise ValueError(f"atom_pages must be keyed by atom ids, got {atom_id!r}")
            if not isinstance(window, AtomPages):
                raise ValueError(f"atom_pages[{atom_id!r}] must be an AtomPages record")
            for page in range(window.first, window.last + 1):
                if page not in self.pages:
                    raise ValueError(
                        f"atom_pages[{atom_id!r}] window covers page {page}, which has no page record"
                    )
        for atom_id, record in self.atoms.items():
            if not (isinstance(atom_id, str) and atom_id):
                raise ValueError(f"atoms must be keyed by atom ids, got {atom_id!r}")
            if not isinstance(record, AtomRecord):
                raise ValueError(f"atoms[{atom_id!r}] must be an AtomRecord")
            if atom_id not in self.atom_pages:
                raise ValueError(f"atoms[{atom_id!r}] has no atom_pages window — records exist only for located atoms")
            assigned = self.atom_pages[atom_id].assigned
            if self.pages[assigned].status != PAGE_MATCHED:
                # G-12 + DT-8's scope split, structurally: a routed page's atoms stay pending
                # (absent from this map) and auto-absents exist only on accepted pages, so an atom
                # record on a non-matched page is an absent-write before verdict.
                raise ValueError(
                    f"atoms[{atom_id!r}] sits on page {assigned} with status "
                    f"{self.pages[assigned].status!r} — atom records exist only on matched pages "
                    f"(a routed page's atoms stay pending, never written; G-12)"
                )
            if record.status == ATOM_MATCHED and record.page != assigned:
                raise ValueError(
                    f"atoms[{atom_id!r}] is matched on page {record.page} but assigned to page "
                    f"{assigned} — the record and the derived attribution disagree"
                )
        if set(self.coverage) != set(COVERAGE_KEYS):
            raise ValueError(
                f"coverage must carry exactly {COVERAGE_KEYS}, got {sorted(self.coverage)}"
            )
        for key in COVERAGE_KEYS:
            value = self.coverage[key]
            if value is None and key in _NULLABLE_COVERAGE_KEYS:
                continue  # unmeasured (no canonical stream at build) — distinct from a measured 0
            if not (_is_int(value) and value >= 0):
                raise ValueError(f"coverage[{key!r}] must be a non-negative integer, got {value!r}")


# --- serialization (envelope ⇄ GeomSidecar) ----------------------------------------------------- #


def _canonical_json(value):
    """Recursively key-sort every nested mapping (lists keep their order — order is data there),
    so serialization is a pure function of *content* all the way down — including a declined
    page's ``verdict`` payload and nested ``backend_params``/``classifier_params`` values, the
    byte-stability #40's idempotent replay asserts against."""
    if isinstance(value, Mapping):
        return {k: _canonical_json(value[k]) for k in sorted(value)}
    if isinstance(value, (list, tuple)):
        return [_canonical_json(v) for v in value]
    return value


def _reject_unknown_keys(data: Mapping, allowed: frozenset[str], ctx: str) -> None:
    """A document carrying keys this schema version does not define is a wrong-era or corrupt
    file; loading it with silent field loss would be a non-fail-loud branch in the loader.
    Applied at every mapping level the schema defines (envelope, source_scan, and each record)."""
    unknown = sorted(set(data) - allowed)
    if unknown:
        raise StaleArtifactError(f"malformed geometry sidecar {ctx}: unknown key(s) {unknown}")


_ENVELOPE_KEYS = frozenset(
    {"schema_version", "stale_class", "witness_id", "stream_source_hash", "source_scan",
     "backend_params", "engine_id", "locate_method", "classifier_version", "classifier_params",
     "pages", "atoms", "atom_pages", "coverage"}
)
_SOURCE_SCAN_KEYS = frozenset({"kind", "sha256", "n_pages", "bytes"})
_PAGE_RECORD_KEYS = frozenset(
    {"status", "match_rate", "dropped_boxes", "stage", "signal", "value", "verdict",
     "n_cols", "n_cols_source", "order_qa"}
)
_ATOM_RECORD_KEYS = frozenset({"status", "match_confidence", "page", "bbox", "match_method", "reason"})
_ATOM_PAGES_KEYS = frozenset({"pages", "assigned"})


def _page_record_to_json(record: PageRecord) -> dict:
    out: dict = {"status": record.status}
    for key in ("match_rate", "dropped_boxes", "stage", "signal", "value", "n_cols", "n_cols_source", "order_qa"):
        value = getattr(record, key)
        if value is not None:
            out[key] = value
    if record.verdict is not None:
        out["verdict"] = _canonical_json(record.verdict)
    return out


def _page_record_from_json(data: Mapping) -> PageRecord:
    if not isinstance(data, Mapping):
        raise StaleArtifactError(f"page record must be a JSON object, got {type(data).__name__}")
    _reject_unknown_keys(data, _PAGE_RECORD_KEYS, "page record")
    return PageRecord(
        status=_require(data, "status", "page record"),
        match_rate=data.get("match_rate"),
        dropped_boxes=data.get("dropped_boxes"),
        stage=data.get("stage"),
        signal=data.get("signal"),
        value=data.get("value"),
        verdict=data.get("verdict"),
        n_cols=data.get("n_cols"),
        n_cols_source=data.get("n_cols_source"),
        order_qa=data.get("order_qa"),
    )


def _atom_record_to_json(record: AtomRecord) -> dict:
    out: dict = {"status": record.status, "match_confidence": record.match_confidence}
    if record.status == ATOM_MATCHED:
        out["page"] = record.page
        out["bbox"] = list(record.bbox)
        out["match_method"] = record.match_method
    else:
        out["reason"] = record.reason
    return out


def _atom_record_from_json(data: Mapping) -> AtomRecord:
    if not isinstance(data, Mapping):
        raise StaleArtifactError(f"atom record must be a JSON object, got {type(data).__name__}")
    _reject_unknown_keys(data, _ATOM_RECORD_KEYS, "atom record")
    bbox = data.get("bbox")
    return AtomRecord(
        status=_require(data, "status", "atom record"),
        match_confidence=_require(data, "match_confidence", "atom record"),
        page=data.get("page"),
        bbox=tuple(bbox) if bbox is not None else None,
        match_method=data.get("match_method"),
        reason=data.get("reason"),
    )


def _atom_pages_to_json(window: AtomPages) -> dict:
    return {"pages": [window.first, window.last], "assigned": window.assigned}


def _atom_pages_from_json(data: Mapping) -> AtomPages:
    if not isinstance(data, Mapping):
        raise StaleArtifactError(f"atom_pages record must be a JSON object, got {type(data).__name__}")
    _reject_unknown_keys(data, _ATOM_PAGES_KEYS, "atom_pages record")
    pages = _require(data, "pages", "atom_pages record")
    if not isinstance(pages, (list, tuple)) or len(pages) != 2:
        raise StaleArtifactError(f"atom_pages.pages must be [first, last], got {pages!r}")
    return AtomPages(first=pages[0], last=pages[1], assigned=_require(data, "assigned", "atom_pages record"))


def to_json(sidecar: GeomSidecar) -> dict:
    """The persisted envelope for ``sidecar``, a pure function of the sidecar's *content*: the
    fixed-schema levels (envelope, ``coverage``) emit in schema order, and every *dynamic* mapping
    is key-sorted (pages numerically, atoms lexicographically, nested payloads recursively via
    ``_canonical_json``) — the byte-stability the G-24 determinism red and #40's idempotent
    replay both assert against."""
    envelope: dict = {
        "schema_version": sidecar.schema_version,
        "stale_class": GEOM_SIDECAR_STALE_CLASS,
        "witness_id": sidecar.witness_id,
        "stream_source_hash": sidecar.stream_source_hash,
        "source_scan": {
            "kind": sidecar.source_scan.kind,
            "sha256": sidecar.source_scan.sha256,
            "n_pages": sidecar.source_scan.n_pages,
            "bytes": sidecar.source_scan.n_bytes,
        },
        "backend_params": _canonical_json(sidecar.backend_params),
        "engine_id": sidecar.engine_id,
        "locate_method": sidecar.locate_method,
        "classifier_version": sidecar.classifier_version,
        "classifier_params": (
            _canonical_json(sidecar.classifier_params)
            if sidecar.classifier_params is not None
            else None
        ),
        "pages": {str(p): _page_record_to_json(sidecar.pages[p]) for p in sorted(sidecar.pages)},
        "atoms": {a: _atom_record_to_json(sidecar.atoms[a]) for a in sorted(sidecar.atoms)},
        "atom_pages": {a: _atom_pages_to_json(sidecar.atom_pages[a]) for a in sorted(sidecar.atom_pages)},
        "coverage": {k: sidecar.coverage[k] for k in COVERAGE_KEYS},
    }
    return envelope


def from_json(data: Mapping) -> GeomSidecar:
    """Parse + validate a persisted envelope, or fail loud (the total load-boundary contract):
    a valid :class:`GeomSidecar` or :class:`~engine.errors.StaleArtifactError`, never a bare
    traceback (G-18)."""
    if not isinstance(data, Mapping):
        raise StaleArtifactError(
            f"geometry-sidecar envelope must be a JSON object, got {type(data).__name__}"
        )
    version = _require(data, "schema_version", "envelope")
    if version != GEOM_SIDECAR_SCHEMA_VERSION:
        raise StaleArtifactError(
            f"geometry-sidecar schema version {version!r} != current {GEOM_SIDECAR_SCHEMA_VERSION!r} "
            f"(stale class {GEOM_SIDECAR_STALE_CLASS!r}) — regenerate the sidecar"
        )
    stale_class = _require(data, "stale_class", "envelope")
    if stale_class != GEOM_SIDECAR_STALE_CLASS:
        raise StaleArtifactError(
            f"stale_class {stale_class!r} != {GEOM_SIDECAR_STALE_CLASS!r} — not a geometry sidecar "
            f"(a different persisted layer, or a malformed file)"
        )
    _reject_unknown_keys(data, _ENVELOPE_KEYS, "envelope")
    try:
        scan = _require(data, "source_scan", "envelope")
        if not isinstance(scan, Mapping):
            raise StaleArtifactError(f"source_scan must be a JSON object, got {type(scan).__name__}")
        _reject_unknown_keys(scan, _SOURCE_SCAN_KEYS, "source_scan")
        source_scan = SourceScan(
            kind=_require(scan, "kind", "source_scan"),
            sha256=_require(scan, "sha256", "source_scan"),
            n_pages=_require(scan, "n_pages", "source_scan"),
            n_bytes=_require(scan, "bytes", "source_scan"),
        )
        raw_pages = _require(data, "pages", "envelope")
        if not isinstance(raw_pages, Mapping):
            raise StaleArtifactError(f"pages must be a JSON object, got {type(raw_pages).__name__}")
        pages: dict[int, PageRecord] = {}
        for key, record in raw_pages.items():
            if not (isinstance(key, str) and key.isdigit()):
                raise StaleArtifactError(f"pages keys must be scan-page integers, got {key!r}")
            pages[int(key)] = _page_record_from_json(record)
        raw_atoms = _require(data, "atoms", "envelope")
        if not isinstance(raw_atoms, Mapping):
            raise StaleArtifactError(f"atoms must be a JSON object, got {type(raw_atoms).__name__}")
        raw_windows = _require(data, "atom_pages", "envelope")
        if not isinstance(raw_windows, Mapping):
            raise StaleArtifactError(f"atom_pages must be a JSON object, got {type(raw_windows).__name__}")
        return GeomSidecar(
            witness_id=_require(data, "witness_id", "envelope"),
            stream_source_hash=_require(data, "stream_source_hash", "envelope"),
            source_scan=source_scan,
            backend_params=_require(data, "backend_params", "envelope"),
            engine_id=_require(data, "engine_id", "envelope"),
            locate_method=_require(data, "locate_method", "envelope"),
            pages=pages,
            atoms={a: _atom_record_from_json(r) for a, r in raw_atoms.items()},
            atom_pages={a: _atom_pages_from_json(w) for a, w in raw_windows.items()},
            coverage=_require(data, "coverage", "envelope"),
            classifier_version=data.get("classifier_version"),
            classifier_params=data.get("classifier_params"),
            schema_version=version,
        )
    except StaleArtifactError:
        raise
    except (ValueError, TypeError) as exc:
        # A model-invariant violation (bad status, invented-geometry shape, G-12 scope fault) or a
        # wrong-typed field in a *persisted* sidecar is corrupt data, not an in-memory programming
        # error: surface it through the load-boundary contract.
        raise StaleArtifactError(f"malformed geometry sidecar: {exc}") from exc


# --- persistence (atomic JSON under data/geometry/) --------------------------------------------- #


def geom_sidecar_path(workspace: BookWorkspace, witness_id: str) -> Path:
    """The containment-checked path to ``<work>/data/geometry/{witness_id}_geom.json``."""
    _check_witness_id(witness_id)
    return workspace.resolve(GEOMETRY_AREA, GEOMETRY_SUBDIR, f"{witness_id}_geom.json")


def save_geom_sidecar(workspace: BookWorkspace, sidecar: GeomSidecar) -> Path:
    """Persist ``sidecar`` atomically; return the path.

    Generation guard (G-19, the regen-guard posture): if a sidecar already exists at the target,
    its scan identity must agree with the one being written — a regeneration whose
    ``source_scan.sha256`` or page count disagrees fails loud
    (:class:`~engine.errors.StaleArtifactError`), because boxes from a *different* scan silently
    replacing boxes an earlier run measured is exactly the drift the fingerprint exists to catch.
    An existing file that cannot even be parsed also refuses (do not trust the silent path); the
    sidecar is disposable, so the deliberate human escape is deleting the stale file.
    """
    path = geom_sidecar_path(workspace, sidecar.witness_id)
    if path.is_file():
        try:
            existing = read_json(path)
        except (json.JSONDecodeError, OSError, UnicodeDecodeError, RecursionError) as exc:
            raise StaleArtifactError(
                f"existing geometry sidecar at {path} is unreadable ({exc}) — refusing to clobber "
                f"it silently; delete the stale file to regenerate"
            ) from exc
        old_scan = existing.get("source_scan") if isinstance(existing, Mapping) else None
        if not isinstance(old_scan, Mapping):
            raise StaleArtifactError(
                f"existing geometry sidecar at {path} carries no source_scan fingerprint — "
                f"refusing to clobber it silently; delete the stale file to regenerate"
            )
        new = sidecar.source_scan
        if old_scan.get("sha256") != new.sha256 or old_scan.get("n_pages") != new.n_pages:
            raise StaleArtifactError(
                f"geometry-sidecar regeneration for witness {sidecar.witness_id!r} disagrees with "
                f"the existing sidecar's scan identity (existing sha256={old_scan.get('sha256')!r} "
                f"n_pages={old_scan.get('n_pages')!r}, new sha256={new.sha256!r} "
                f"n_pages={new.n_pages!r}) — the scan changed under the sidecar (G-19); delete the "
                f"stale sidecar only as a deliberate act"
            )
    path.parent.mkdir(parents=True, exist_ok=True)
    atomic_write_json(path, to_json(sidecar))
    return path


def load_geom_sidecar(workspace: BookWorkspace, witness_id: str) -> GeomSidecar:
    """Read + validate the sidecar for ``witness_id``, or fail loud (G-18): absent →
    :class:`~engine.errors.MissingInputError`; non-JSON / stale / malformed / id-mismatched →
    :class:`~engine.errors.StaleArtifactError`."""
    path = geom_sidecar_path(workspace, witness_id)
    if not path.is_file():
        raise MissingInputError(f"geometry sidecar for witness {witness_id!r} not found at {path}")
    try:
        data = read_json(path)
    except (json.JSONDecodeError, OSError, UnicodeDecodeError, RecursionError) as exc:
        # The full house wrap set (errors.py load-boundary contract): non-JSON, unreadable,
        # non-UTF-8, and parse-depth blowup are all present-but-unloadable — StaleArtifactError,
        # never a bare traceback (G-18's totality).
        raise StaleArtifactError(
            f"geometry sidecar for witness {witness_id!r} at {path} is unloadable: {exc}"
        ) from exc
    sidecar = from_json(data)
    if sidecar.witness_id != witness_id:
        raise StaleArtifactError(
            f"geometry-sidecar id mismatch: file for {witness_id!r} carries witness_id "
            f"{sidecar.witness_id!r}"
        )
    return sidecar


def with_detector_fields(
    sidecar: GeomSidecar, by_page: Mapping[int, Mapping[str, object]]
) -> GeomSidecar:
    """Populate the schema-v2 detector fields on matched pages (DT-12 — the S2.2 ``order_qa`` feed).

    ``by_page`` maps a scan page → ``{n_cols, n_cols_source, order_qa}`` (the resolved column
    decision + the QA cross-check). Only **matched** pages carry detector fields, so ``by_page``
    must key matched pages only — a page that is routed/declined/absent is an error (the caller
    computed a verdict for a page the sidecar cannot attach it to), never a silent skip. Returns a
    new sidecar; the input is untouched (frozen)."""
    if not by_page:
        return sidecar
    allowed = frozenset({"n_cols", "n_cols_source", "order_qa"})
    new_pages = dict(sidecar.pages)
    for page, fields in by_page.items():
        unknown = sorted(set(fields) - allowed)
        if unknown:
            # Reject a typo'd key rather than silently dropping it (partial data loss) — the same
            # posture as the loaders' _reject_unknown_keys.
            raise ValueError(
                f"with_detector_fields got unknown field key(s) {unknown} for page {page} — the "
                f"detector fields are exactly {sorted(allowed)}"
            )
        record = new_pages.get(page)
        if record is None or record.status != PAGE_MATCHED:
            status = record.status if record is not None else "absent"
            raise ValueError(
                f"cannot attach detector fields to page {page}: its record is {status!r}, not "
                f"{PAGE_MATCHED!r} — the S2.2 feed measures accepted geometry only"
            )
        new_pages[page] = replace(
            record,
            n_cols=fields.get("n_cols"),
            n_cols_source=fields.get("n_cols_source"),
            order_qa=fields.get("order_qa"),
        )
    return replace(sidecar, pages=new_pages)


def assert_source_scan_matches(sidecar: GeomSidecar, *, sha256: str, n_pages: int) -> None:
    """The replay-side fingerprint check (G-19, DT-12/R15): any seam re-invocation compares the
    recorded scan identity against the live scan and fails loud on mismatch
    (:class:`~engine.errors.StaleArtifactError`) — so a consumer either replays on
    provably-identical inputs or knows it did not."""
    recorded = sidecar.source_scan
    if recorded.sha256 != sha256 or recorded.n_pages != n_pages:
        raise StaleArtifactError(
            f"source scan drifted under the geometry sidecar for witness {sidecar.witness_id!r}: "
            f"recorded sha256={recorded.sha256!r} n_pages={recorded.n_pages}, live sha256={sha256!r} "
            f"n_pages={n_pages} — regenerate the sidecar or restore the recorded scan (G-19)"
        )


# --- P-5 auto-absent tripwire (G-26) ------------------------------------------------------------ #

#: Warn-tier token bands for the auto-absent table (reason × band): the ≤3-token furniture tail,
#: prose-sized atoms at the leg-B floor, and long prose.
_BANDS = (("<=3", 1, TRIPWIRE_PROSE_MIN_TOKENS - 1), ("4-10", TRIPWIRE_PROSE_MIN_TOKENS, 10), (">10", 11, None))


def _band_of(count: int) -> str:
    for name, lo, hi in _BANDS:
        if count >= lo and (hi is None or count <= hi):
            return name
    return _BANDS[0][0]  # count == 0 folds into the shortest band


def assert_auto_absent_tripwire(
    sidecar: GeomSidecar, token_counts: Mapping[str, int]
) -> dict:
    """The P-5 two-leg auto-absent tripwire (RULED 2026-07-03; G-26) — hard-fails on either leg,
    returns the warn-tier stats for the run report.

    Both legs are computed over **accepted pages only**: every record in ``sidecar.atoms`` sits on
    a matched page by model invariant, so the record set *is* the accepted-page population — a
    routed page's pending atoms never enter either numerator or denominator. ``token_counts`` maps
    atom id → DT-8-normalizer token count and must cover every record-bearing atom (a missing
    count is a caller error, ``ValueError`` — a silently shrunken denominator would loosen both
    legs).

    - **Leg A (token mass):** auto-absent token mass / accepted-page token mass >
      :data:`TRIPWIRE_ABSENT_MASS_MAX` → :class:`~engine.structure.geometry.GeometryError`.
    - **Leg B (scoped count):** among atoms with ≥ :data:`TRIPWIRE_PROSE_MIN_TOKENS` witness
      tokens, auto-absent rate > :data:`TRIPWIRE_PROSE_ABSENT_RATE_MAX` → same.

    A trip means the automation premise failed — fix the matcher; the bar is never raised to
    un-fire a trip (the pre-committed retune protocol, DT-8).
    """
    missing = [a for a in sidecar.atoms if a not in token_counts]
    if missing:
        raise ValueError(
            f"token_counts is missing {len(missing)} record-bearing atom(s) (first: {missing[:3]}) — "
            f"the tripwire denominators must cover every accepted-page atom"
        )

    total_mass = 0
    absent_mass = 0
    prose_total = 0
    prose_absent = 0
    bands: dict[str, dict] = {
        name: {"atoms": 0, "absent_atoms": 0, "token_mass": 0, "absent_token_mass": 0, "reasons": {}}
        for name, _, _ in _BANDS
    }
    confidences: list[float] = []
    for atom_id, record in sidecar.atoms.items():
        count = token_counts[atom_id]
        if not (_is_int(count) and count >= 0):
            raise ValueError(f"token_counts[{atom_id!r}] must be a non-negative integer, got {count!r}")
        band = bands[_band_of(count)]
        band["atoms"] += 1
        band["token_mass"] += count
        total_mass += count
        confidences.append(record.match_confidence)
        if count >= TRIPWIRE_PROSE_MIN_TOKENS:
            prose_total += 1
        if record.status == ATOM_UNMATCHED:
            absent_mass += count
            band["absent_atoms"] += 1
            band["absent_token_mass"] += count
            band["reasons"][record.reason] = band["reasons"].get(record.reason, 0) + 1
            if count >= TRIPWIRE_PROSE_MIN_TOKENS:
                prose_absent += 1

    absent_mass_rate = (absent_mass / total_mass) if total_mass else 0.0
    prose_absent_rate = (prose_absent / prose_total) if prose_total else 0.0

    if absent_mass_rate > TRIPWIRE_ABSENT_MASS_MAX:
        raise GeometryError(
            f"auto-absent tripwire leg A fired: {absent_mass_rate:.4f} of accepted-page token mass "
            f"is auto-absent (> {TRIPWIRE_ABSENT_MASS_MAX}) — real prose mass is absent; the "
            f"automation premise failed. Fix the matcher; never raise the bar to un-fire a trip "
            f"(P-5/G-26)"
        )
    if prose_absent_rate > TRIPWIRE_PROSE_ABSENT_RATE_MAX:
        raise GeometryError(
            f"auto-absent tripwire leg B fired: {prose_absent_rate:.4f} of "
            f">={TRIPWIRE_PROSE_MIN_TOKENS}-token atoms on accepted pages are auto-absent "
            f"(> {TRIPWIRE_PROSE_ABSENT_RATE_MAX}) — systematic absence, never honest residue; the "
            f"automation premise failed. Fix the matcher; never raise the bar to un-fire a trip "
            f"(P-5/G-26)"
        )

    histogram: dict[str, int] = {}
    for i in range(10):
        lo = i / 10
        hi = (i + 1) / 10
        key = f"{lo:.1f}-{hi:.1f}"
        histogram[key] = sum(1 for c in confidences if (lo <= c < hi) or (i == 9 and c == 1.0))
    flags = [
        f"band {name}: auto-absent token mass {band['absent_token_mass']}/{total_mass} exceeds "
        f"{TRIPWIRE_WARN_BAND_MASS:.0%} of accepted-page token mass"
        for name, band in bands.items()
        if total_mass and band["absent_token_mass"] / total_mass > TRIPWIRE_WARN_BAND_MASS
    ]
    return {
        "absent_token_mass_rate": absent_mass_rate,
        "prose_absent_rate": prose_absent_rate,
        "bands": bands,
        "confidence_histogram": histogram,
        "flags": flags,
    }
